/* eslint-disable @next/next/no-img-element */
import Link from 'next/link'
import React from 'react'

const AboutUs = () => {
  return (
    <main className=''>
      <section className='relative bgAnimation h-screen pt-32'>
        <div className='px-12 space-y-5'>
          <h1 className='text-6xl font-extrabold font-druk'>
            <span className='bg-clip-text text-white/40'>Welcome</span> to
            <br />
            the <span className='bg-clip-text text-white/40'>Future</span> of
            <br />
            Music <span className='bg-clip-text text-white/40'>Streaming</span>
          </h1>
          <p className='text-white font-gilroy text-xl'>Embrace the Power of Crypto Payments with Web2.5!</p>
        </div>
      </section>
      <section className='py-20 px-12'>
        <h2 className='text-center text-6xl font-gilroy font-bold text-cyanSky pb-12'>Unleashing the Potential</h2>
        <p className='px-20 text-xl font-semibold text-black/85'>
          In the rapidly evolving landscape of digital entertainment, the fusion of cutting-edge technology and innovative financial solutions has given birth to a new era - Web2.5 music streaming. Elevate your music experience by diving into the world of crypto payments, where seamless transactions meet the rhythm of your favorite tunes.
        </p>
        <div className='flex gap-x-6 py-20'>
          <div className='border shadow-lg rounded-md p-8 space-y-4'>
            <div className='bg-[#9c42f5] w-14 rounded-full p-2 shadow-inner border border-[#9c42f5]'>
              <img src="/images/cubes.png" alt="cubes" className='' />
            </div>
            <div className='space-y-1'>
              <h3 className='font-bold text-slate-600 text-lg'>Embrace Decentralisation</h3>
              <p className='text-sm'>
                Say goodbye to traditional payment gateways and welcome decentralization with open arms. Web2.5 music streaming powered by crypto payments ensures that you have full control over your transactions. No intermediaries, no delays - just direct, peer-to-peer transactions that empower both artists and listeners.
              </p>
            </div>
          </div>
          <div className='border shadow-lg rounded-md p-8 space-y-4'>
            <div className='bg-[#4befc4] w-14 rounded-full p-2 shadow-inner border border-[#4befc4]'>
              <img src="/images/credit-card.png" alt="cubes" className='' />
            </div>
            <div className='space-y-1'>
              <h3 className='font-bold text-slate-600 text-lg'>Seamless Transactions</h3>
              <p className='text-sm'>
                Gone are the days of complex payment processes. With crypto payments integrated into Web2.5 music streaming, enjoy the simplicity of swift and secure transactions. Whether you&apos;re subscribing to premium features, supporting your favorite artists, or exploring exclusive content, every transaction is as smooth as your favorite track&apos;s melody.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className='py-20 sectionClip bg-gray-50 px-12'>
        <h2 className='textGradient text-7xl font-gilroy text-center font-bold leading-relaxed'>Empowering Artists</h2>
        <p className='px-20 text-xl font-semibold text-black/85'>
          In an era dominated by digital innovation, the need to empower musicians has never been more critical. As the music industry evolves, Web2.5 music streaming takes a stand to ensure that artists not only survive but thrive in this dynamic landscape. Let&apos;s delve into how this revolution is reshaping the way musicians are compensated and recognized.
        </p>
        <div className='pt-16 space-y-8'>
          <div className='border-b pb-8'>
            <h3 className='text-3xl font-bold text-teal-500 mb-3'>Transparent Transactions</h3>
            <p className=''>
              In the traditional music industry, opaque financial structures often left artists in the dark about the fate of their earnings. Enter blockchain technology - the backbone of transparent transactions in Web2.5 music streaming. Blockchain ensures a decentralized ledger where every transaction is recorded, providing an immutable and publicly accessible record of artist compensation. This newfound transparency guarantees that artists receive their fair share of the revenue generated by their creative endeavors. By embracing blockchain, we usher in an era where the mystery surrounding artist compensation is replaced by clarity and trust.
            </p>
          </div>
          <div className='border-b pb-8'>
            <h3 className='text-3xl font-bold text-[#9c42f5] mb-3'>Recognition and Rewards</h3>
            <p>
              Beyond the financial aspect, Web2.5 music streaming introduces a paradigm shift in how artists are recognized and rewarded. No longer confined to the limitations of traditional royalties, artists now have the opportunity to directly connect with their audience. Through innovative features, fans can support their favorite musicians more directly - whether it&apos;s through exclusive memberships, virtual merchandise, or unique experiences.
              <br />
              By actively participating in supporting artists, listeners become integral contributors to the creative process. This newfound connection fosters a symbiotic relationship between artists and their audience, ensuring that the music ecosystem flourishes. We encourage you to explore the diverse ways you can support and engage with your favorite musicians, transforming the act of streaming music into a collaborative celebration of artistic expression. Join us in championing a future where artists receive not only fair compensation but also the recognition and rewards they truly deserve.
            </p>
          </div>
          <div className='pb-8'>
            <h3 className='text-3xl font-bold text-[#4579f5] mb-3'>Encouraging users to support their favorite musicians</h3>
            <p>
              Empower the voices that resonate with you. Choose to actively support the musicians who soundtrack your life. Your contribution goes beyond a simple transaction - it becomes a catalyst for a thriving creative community. Join the movement, engage with exclusive content, and be a patron of the arts in the digital age. Together, let&apos;s amplify the impact of music and ensure that every artist receives the acknowledgment and compensation that reflects their talent and dedication. Your support matters - become a driving force behind the artists who enrich our lives with their incredible soundscapes.
            </p>
          </div>
        </div>
      </section>
      <section className='py-20 px-12'>
        <h2 className='text-center text-6xl font-gilroy font-extrabold text-cyanSky pb-12'>Our Artists</h2>
        <p className='px-20 text-xl font-semibold text-[#4579f5] text-center'>
          Introducing the early adopters & DJ playlists
        </p>
        <div className='flex justify-center flex-wrap gap-8 my-12'>
          <div className='flex flex-col items-center justify-center'>
            <img
              src="https://www.billboard.com/wp-content/uploads/media/Paul-Blair-DJ-White-Shadow-2016-press-billboard-650.jpg?w=650&h=430&crop=1"
              alt="artist"
              className='w-44 h-44 rounded-full object-cover'
            />
            <div className='flex flex-col justify-center items-center pt-3'>
              <h3 className='text-[#9c42f5] text-sm font-semibold'>DJWS</h3>
              <h4 className='text-xs font-extralight'>USA</h4>
            </div>
          </div>
          <div className='flex flex-col items-center justify-center'>
            <img
              src="https://www.ticketcorner.ch/obj/media/CH-eventim/galery/kuenstler/d/dj-idem_01.jpg"
              alt="artist"
              className='w-44 h-44 rounded-full object-cover'
            />
            <div className='flex flex-col justify-center items-center pt-3'>
              <h3 className='text-[#9c42f5] text-sm font-semibold'>DJ Idem</h3>
              <h4 className='text-xs font-extralight'>Switzerland</h4>
            </div>
          </div>
          <div className='flex flex-col items-center justify-center'>
            <img
              src="https://media.licdn.com/dms/image/C4D03AQG5I1C-FzYjfw/profile-displayphoto-shrink_400_400/0/1614882349776?e=1710979200&v=beta&t=qp6m-312zi_zGAeE8aQmPR79TMCm4Xt4djFGgvsayH4"
              alt="artist"
              className='w-44 h-44 rounded-full object-cover object-left'
            />
            <div className='flex flex-col justify-center items-center pt-3'>
              <h3 className='text-[#9c42f5] text-sm font-semibold'>Willie Taylor</h3>
              <h4 className='text-xs font-extralight'>USA</h4>
            </div>
          </div>
          <div className='flex flex-col items-center justify-center'>
            <img
              src="https://www.billboard.com/wp-content/uploads/media/Paul-Blair-DJ-White-Shadow-2016-press-billboard-650.jpg?w=650&h=430&crop=1"
              alt="artist"
              className='w-44 h-44 rounded-full object-cover'
            />
            <div className='flex flex-col justify-center items-center'>
              <h3 className='text-[#9c42f5] text-sm font-semibold'>Murphy Lee</h3>
              <h4 className='text-xs font-extralight'>USA</h4>
            </div>
          </div>
          <div className='flex flex-col items-center justify-center'>
            <img
              src="https://www.thehypemagazine.com/wp-content/uploads/2023/02/Murph-2.jpg"
              alt="artist"
              className='w-44 h-44 rounded-full object-cover'
            />
            <div className='flex flex-col justify-center items-center pt-3'>
              <h3 className='text-[#9c42f5] text-sm font-semibold'>Mystical</h3>
              <h4 className='text-xs font-extralight'>USA</h4>
            </div>
          </div>
        </div>
      </section>
      <section className='py-32 bgCta px-12'>
        <h2 className='text-white text-6xl font-extrabold font-gilroy'>Ready to Redefine Your Experience?</h2>
        <h4 className='text-4xl mt-12 font-bold text-white'>Express excitement for the future <br />
          where Web2.5 meets the beat
          <br />
          of the blockchain.
        </h4>
        <div className='py-8 pb-20'>
        <Link href={'/account/signup'} className=' justify-center py-2.5 items-center w-44 gap-x-4 orangeToPink group flex'>Get Started <p className='group-hover:translate-x-2 text-lg transition-all duration-300 ease-in-out'>&rarr;</p></Link>
        </div>
      </section>
    </main>
  )
}

export default AboutUs